baseurl = "https://hugodocs.info"
buildDrafts = false
buildFuture = false
canonifyurls = true
# Pointing to this file
config = "config.toml"
copyright = ""
defaultContentLanguage = "en"
# Set to true to keep url path preserve casing (eg, for sections)
disablePathToLower = false
# Site-level description
description = ""
# Allows use of emoji shorthand directly in content
enableEmoji = true
# Set the unicode character used for the "return" link in page footnotes.
footnotereturnlinkcontents = "↩"
# Create an array of files you don't want hugo to build
ignoreFiles = []
languageCode = "en-us"
# Enable Logging
log = true
# Log Filepath (if set, logging enabled automatically)
logFile = ""
# This accepts yaml, toml, or json
metaDataFormat = "yaml"
# This intelligently adds an "s" to the titles of list pages
pluralizelisttitles = false
relativeURLs = true
# Display memory and timing of different steps of the program
stepAnalysis = true
# This is the top-level, global site title
title = "Hugo"
# Change this to your preferred theme
theme = "hugo-docs-concept"
# Set to true to convert mysite/section/ to mysite/section.html
uglyURLs = false
verbose = false
verboseLog = false
# Setting this to false will keep hugo from watching for changes during local development
watch = true
# Add GA Tracking Code Here. This leverages a built-in (ie, "internal") partial from HUGO: https://gohugo.io/extras/analytics#configuring-google-analytics
googleAnalytics = "UA-76549364-1"

[permalinks]
  temp = "/:title"

#CUSTOM PARAMS
[params]
  ## Used for views in rendered HTML (i.e., rather than using the .Hugo variable)
  release = "0.20"
  ## Critical Render Path. If true, site style will be embedded in a <style> tag in each html <head> as part of Gulp Build. False puts a typical <link> to the stylesheet in <head> See layouts/partials/style-embed.html
  usecrp = false
  ## Twitter handle without the "@"
  twitterhandle = "GoHugoIO"
  ## Facebook URL
  facebook = ""
  ## Default Image for Social Sharing. This image should live at static/images/
  defaultsocialimage = "hugodefaultsocial.png"
  ## Setting this to true will add a "noindex" to *EVERY* page on the site
  removefromexternalsearch = false
  ## This is used when the BaseURL does not need to modified (eg, in share links or in prerender, prefetch, etc to control for relativeURLs setting); do *not* include trailing slash
  siteaddress = "https://hugodocs.info"
  ## Gh repo for site footer (include trailing slash)
  ghrepo = "https://github.com/spf13/hugo/"
  ### Edit content repo (set to automatically enter "edit" mode; this is good for "improve this page" links)
  ghdocsrepo = "https://github.com/rdwatters/hugo-docs-concept/edit/master/"
  ## Gitter URL
  gitter = "https://gitter.im/spf13/hugo"
  ## Discuss Forum URL
  forum = "https://discuss.gohugo.io"
  ## Google Tag Manager
  gtmid = ""
  # Set to true to include a CDN call to FontAwesome (note that Hugo currently hosts its own FA (see pipeline/scss/_variables.scss) if needed, but leverages a custom Fontello font or icons, including the "H" and "Gopher" icons for code blocks)
  usefontawesome = false

# MARKDOWN
## Configuration for BlackFriday markdown parser: https://github.com/russross/blackfriday
[blackfriday]
	plainIDAnchors = true
	hrefTargetBlank = true
  angledQuotes = false
  latexDashes = true

## As of v0.20, all content files include a default "categories" value that's the same as the section. This was a cheap future-proofing method and should/could be changed accordingly.
[taxonomies]
  tag = "tags"
