baseurl = "https://hugodocs.info"
canonifyurls = true
# Pointing to this file
config = "config.toml"
enableGitInfo = true
paginate=  100
copyright = ""
defaultContentLanguage = "en"
# Set to true to keep url path preserve casing (eg, for sections)
disablePathToLower = false

# Allows use of emoji shorthand directly in content
enableEmoji = true
# Set the unicode character used for the "return" link in page footnotes.
footnotereturnlinkcontents = "↩"
# Create an array of files you don't want hugo to build
ignoreFiles = []
languageCode = "en-us"
# Enable Logging
log = true
# Log Filepath (if set, logging enabled automatically)
logFile = ""
# This accepts yaml, toml, or json
metaDataFormat = "yaml"
# This intelligently adds an "s" to the titles of list pages
pluralizelisttitles = false
relativeURLs = true
# Display memory and timing of different steps of the program
stepAnalysis = true
# This is the top-level, global site title
title = "Hugo"

# Change this once you've created your theme
theme = "gohugoioTheme"

# Set to true to convert mysite/section/ to mysite/section.html
uglyURLs = false
verbose = false
verboseLog = false
# Setting this to false will keep hugo from watching for changes during local development
watch = true
# Add GA Tracking Code Here. This leverages a built-in (ie, "internal") partial from HUGO: https://gohugo.io/extras/analytics#configuring-google-analytics
googleAnalytics = "UA-76549364-1"

[social]
twitter = "GoHugoIO"


#CUSTOM PARAMS
[params]
  description = "The world’s fastest framework for building websites"
  ## Used for views in rendered HTML (i.e., rather than using the .Hugo variable)
  release = "0.20"
  ## Setting this to true will add a "noindex" to *EVERY* page on the site
  removefromexternalsearch = false
  ## This is used when the BaseURL does not need to modified (eg, in share links or in prerender, prefetch, etc to control for relativeURLs setting); do *not* include trailing slash
  siteaddress = "https://hugodocs.info"
  ## Gh repo for site footer (include trailing slash)
  ghrepo = "https://github.com/spf13/hugo/"
  ### Edit content repo (set to automatically enter "edit" mode; this is good for "improve this page" links)
  ghdocsrepo = "https://github.com/spf13/hugo/tree/master/docs"
  ## Gitter URL
  gitter = "https://gitter.im/spf13/hugo"
  ## Discuss Forum URL
  forum = "https://discuss.gohugo.io"
  ## Google Tag Manager
  gtmid = ""

  flex_box_interior_classes = "flex-auto w-100 w-40-l mr3 mb3 bg-white ba b--moon-gray nested-copy-line-height"

  #sidebar_direction = "sidebar_left"

# MARKDOWN
## Configuration for BlackFriday markdown parser: https://github.com/russross/blackfriday
[blackfriday]
	plainIDAnchors = true
	hrefTargetBlank = true
  angledQuotes = false
  latexDashes = true

## As of v0.20, all content files include a default "categories" value that's the same as the section. This was a cheap future-proofing method and should/could be changed accordingly.
[taxonomies]
  tag = "tags"
  category = "categories"


# High level items

[[menu.docs]]
  name = "About Hugo"
  weight = 1
  identifier = "about"
  url = "/about/"

[[menu.docs]]
  name = "Getting Started"
  weight = 5
  identifier = "getting-started"
  url = "/getting-started/"


[[menu.docs]]
  name = "Themes"
  weight = 15
  identifier = "themes"
  post = "break"
  url = "/themes/"

# Core Menus

[[menu.docs]]
  name = "Content Management"
  weight = 20
  identifier = "content-management"
  post = "expanded"
  url = "/content-management/"

[[menu.docs]]
  name = "Templates"
  weight = 25
  identifier = "templates"

  url = "/templates/"

[[menu.docs]]
  name = "Functions"
  weight = 30
  identifier = "functions"
  url = "/functions/"

[[menu.docs]]
  name = "Variables"
  weight = 35
  identifier = "variables"
  url = "/variables/"

[[menu.docs]]
  name = "CLI"
  weight = 40
  post = "break"
  identifier = "commands"
  url = "/commands/"



# LOW LEVEL ITEMS


[[menu.docs]]
  name = "Troubleshooting"
  weight = 60
  identifier = "troubleshooting"
  url = "/troubleshooting/"

[[menu.docs]]
  name = "Tools"
  weight = 70
  identifier = "tools"
  url = "/tools/"

[[menu.docs]]
  name = "Hosting & Deployment"
  weight = 80
  identifier = "hosting-and-deployment"
  url = "/hosting-and-deployment/"

[[menu.docs]]
  name = "Contribute"
  weight = 100
  post = "break"
  identifier = "contribute"
  url = "/contribute/"

[[menu.docs]]
  name = "Tags"
  weight = 120
  identifier = "tags"
  url = "/tags/"


# [[menu.docs]]
#   name = "Categories"
#   weight = 140
#   identifier = "categories"
#   url = "/categories/"

######## QUICKLINKS

  [[menu.quicklinks]]
    name = "Fundamentals"
    weight = 1
    identifier = "fundamentals"
    url = "/tags/fundamentals/"




######## GLOBAL ITEMS TO BE SHARED WITH THE HUGO siteaddress

[[menu.global]]
    name = "News"
    weight = 1
    identifier = "news"
    url = "/news/"

  [[menu.global]]
    name = "Docs"
    weight = 5
    identifier = "docs"
    url = "/documentation/"

  [[menu.global]]
    name = "Themes"
    weight = 10
    identifier = "themes"
    url = "http://themes.gohugo.io/"

  # Anything with a weight > 100 gets an external icon
  [[menu.global]]
    name = "Community"
    weight = 150
    icon = true
    identifier = "community"
    post = "external"
    url = "https://discuss.gohugo.io/"


  [[menu.global]]
    name = "GitHub"
    weight = 200
    identifier = "github"
    post = "external"
    url = "https://github.com/spf13/hugo"
